name: Docker Build CI

on:
  push:
  workflow_dispatch:

jobs:
  build-fast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
      - run: |
          find .
      - name: test submodule viaSsh
        run: |
          [ $(find ./viaSsh | wc -l) -ge 5 ]
      - name: test submodule viaHttps
        run: |
          [ $(find ./viaHttps | wc -l) -ge 5 ]
      - name: test lfs file
        run: |
          [ $(stat -c %s test.bin) -ge 800000 ]
