name: Docker Build CI

on:
  push:
  workflow_dispatch:

jobs:
  build-fast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
      - run: |
          find .
      - name: test viaSsh
        run:
          [ $(find ./viaSsh | wc -l) -ge 5 ]
      - name: test viaHttps
        run:
          [ $(find ./viaHttps | wc -l) -ge 5 ]
